FROM node:9

EXPOSE 4200

MAINTAINER shinto cv

RUN npm config set unsafe-perm=true && \
    npm install -g @angular/cli@1.5.0

WORKDIR /admin-solution

ENTRYPOINT ["/admin-solution/deploy/entrypoint.sh"]

# CMD ["/bin/sh"]
